audio_loader:
  supported_formats:
    - ext: "wav"
      priority: 1
      decoder: "scipy"
      options:
        dtype: "float32"
    - ext: "mp3"
      priority: 2
      decoder: "librosa"
      options:
        res_type: "kaiser_best"
    - ext: "flac"
      priority: 1
      decoder: "soundfile"
      options:
        always_2d: false
    - ext: "ogg"
      priority: 2
      decoder: "audioread"
      options:
        backend: "ffmpeg"
  
  preprocessing:
    target_sample_rate: 16000
    target_channels: 1
    target_bit_depth: 32
    normalize_method: "db"
    target_db: -20.0
    trim_silence: true
    silence_threshold: -40  # dB
    
  validation:
    min_duration: 0.1  # seconds
    max_duration: 3600  # seconds
    max_file_size: 2048  # MB
    check_corruption: true
    min_amplitude: 0.001
    check_clipping: true
    
  cache:
    enabled: true
    max_size: 1000  # number of files
    ttl: 3600  # seconds
    backend: "lru"  # or "redis"
    
  streaming:
    chunk_size: 1048576  # 1MB in samples
    overlap: 0
    enabled_for_size_above: 104857600  # 100MB